/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupLayoutRouteImport } from './routes/signup.layout'
import { Route as SignupClientRouteImport } from './routes/signup/client'
import { Route as SignupAffiliateRouteImport } from './routes/signup/affiliate'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupLayoutRoute = SignupLayoutRouteImport.update({
  id: '/signup/layout',
  path: '/signup/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupClientRoute = SignupClientRouteImport.update({
  id: '/signup/client',
  path: '/signup/client',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupAffiliateRoute = SignupAffiliateRouteImport.update({
  id: '/signup/affiliate',
  path: '/signup/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup/affiliate': typeof SignupAffiliateRoute
  '/signup/client': typeof SignupClientRoute
  '/signup/layout': typeof SignupLayoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup/affiliate': typeof SignupAffiliateRoute
  '/signup/client': typeof SignupClientRoute
  '/signup/layout': typeof SignupLayoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup/affiliate': typeof SignupAffiliateRoute
  '/signup/client': typeof SignupClientRoute
  '/signup/layout': typeof SignupLayoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup/affiliate'
    | '/signup/client'
    | '/signup/layout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup/affiliate' | '/signup/client' | '/signup/layout'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup/affiliate'
    | '/signup/client'
    | '/signup/layout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupAffiliateRoute: typeof SignupAffiliateRoute
  SignupClientRoute: typeof SignupClientRoute
  SignupLayoutRoute: typeof SignupLayoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/layout': {
      id: '/signup/layout'
      path: '/signup/layout'
      fullPath: '/signup/layout'
      preLoaderRoute: typeof SignupLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/client': {
      id: '/signup/client'
      path: '/signup/client'
      fullPath: '/signup/client'
      preLoaderRoute: typeof SignupClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/affiliate': {
      id: '/signup/affiliate'
      path: '/signup/affiliate'
      fullPath: '/signup/affiliate'
      preLoaderRoute: typeof SignupAffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupAffiliateRoute: SignupAffiliateRoute,
  SignupClientRoute: SignupClientRoute,
  SignupLayoutRoute: SignupLayoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
