/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupClientRouteImport } from './routes/signup/client'
import { Route as SignupAffiliateRouteImport } from './routes/signup/affiliate'
import { Route as DashboardAffiliateRouteImport } from './routes/dashboard/affiliate'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupClientRoute = SignupClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => SignupRoute,
} as any)
const SignupAffiliateRoute = SignupAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => SignupRoute,
} as any)
const DashboardAffiliateRoute = DashboardAffiliateRouteImport.update({
  id: '/dashboard/affiliate',
  path: '/dashboard/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRouteWithChildren
  '/dashboard/affiliate': typeof DashboardAffiliateRoute
  '/signup/affiliate': typeof SignupAffiliateRoute
  '/signup/client': typeof SignupClientRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRouteWithChildren
  '/dashboard/affiliate': typeof DashboardAffiliateRoute
  '/signup/affiliate': typeof SignupAffiliateRoute
  '/signup/client': typeof SignupClientRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRouteWithChildren
  '/dashboard/affiliate': typeof DashboardAffiliateRoute
  '/signup/affiliate': typeof SignupAffiliateRoute
  '/signup/client': typeof SignupClientRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/affiliate'
    | '/signup/affiliate'
    | '/signup/client'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/affiliate'
    | '/signup/affiliate'
    | '/signup/client'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/affiliate'
    | '/signup/affiliate'
    | '/signup/client'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRouteWithChildren
  DashboardAffiliateRoute: typeof DashboardAffiliateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/client': {
      id: '/signup/client'
      path: '/client'
      fullPath: '/signup/client'
      preLoaderRoute: typeof SignupClientRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/affiliate': {
      id: '/signup/affiliate'
      path: '/affiliate'
      fullPath: '/signup/affiliate'
      preLoaderRoute: typeof SignupAffiliateRouteImport
      parentRoute: typeof SignupRoute
    }
    '/dashboard/affiliate': {
      id: '/dashboard/affiliate'
      path: '/dashboard/affiliate'
      fullPath: '/dashboard/affiliate'
      preLoaderRoute: typeof DashboardAffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SignupRouteChildren {
  SignupAffiliateRoute: typeof SignupAffiliateRoute
  SignupClientRoute: typeof SignupClientRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupAffiliateRoute: SignupAffiliateRoute,
  SignupClientRoute: SignupClientRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRouteWithChildren,
  DashboardAffiliateRoute: DashboardAffiliateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
